# GitHub nf-core repositories that should be excluded from the website

ignore_repos:
  # Early-stage pipelines
  - genephylo # 2025-02-14
  - moleculardynamics # 2025-08-04
  - tandemrepeat # 2025-11-21
  - crossmirna # 2025-11-21
  - pharmstarcaller # 2026-02-19
  - msproteomics # 2026-03-19
  - eupathpopgen # 2026-09-17

  # Non-pipeline repos
  - .github
  - actions
  - actions-runners
  - agents
  - basic_training
  - configs
  - connectgame
  - hackathon
  - hackathon-infra
  - logos
  - megatest-seqerakit
  - modules
  - modules-template
  - newsletter
  - nf-core-utils
  - nft-tiff
  - nft-utils
  - ops
  - proposals
  - r-nf-core-utils
  - references-assets
  - references-datasheets
  - run-nf-test
  - setup-nextflow
  - setup-nf-test
  - slackbot
  - stats
  - strict-syntax-health
  - sublime
  - test-datasets
  - testpipeline
  - tools
  - vale
  - vscode-extensionpack
  - website

  # Archived repos
  - awsmegatests
  - cookiecutter
  - gh-actions-lint
  - nf-core.github.io
  - prettier-plugin-nextflow
  - tower-action

ignore_topics:
  - nf-core
  - nextflow
  - workflow
  - workflows
  - pipeline
  - pipelines
  - bioinformatics
  - conda
  - containers
  - docker
  - next-generation-sequencing
  - reproducible-research
  - reproducible-science
  - singularity
