<?php
//
// nf-core/tools Version Check
//

header('Content-type: text/plain');

// First - print the latest version.
// This file is automatically generated by the latest tag in the git repository when a new commit is pushed
$version = file_get_contents("../includes/nf-core/tools_version.txt");
preg_replace('/[^\d\.]/', '', $version);
print($version);
