---
title: NF-PCGR Enhancements
category: pipelines
slack: 
intro_video: 
image:
image_alt: sites/main-site/src/assets/images/events/2025/hackathon-march/nf-pcgr.png
leaders:
  - github: [pdiakumis, sigven, yussab, barrydigby]
    name: Youssef Abili 
    slack: https://nfcore.slack.com/archives/CE6SDEDAA/p1674573191030419

---

## Project Overview

The **NF-PCGR** (Nextflow-based Pipeline for Clinical Genome Reports) is an open-source pipeline for generating clinical genome reports using the PCGR framework. 
During this hackathon, we aim to update the functionality of NF-PCGR and try to complete the integration with sarek.

## Goal

By the end of the hackathon, we aim to achieve the following:

- Integrate new variant annotation sources to improve reporting.
- Optimize pipeline execution for better performance.
- Start the integration with nf-core sarek 

## How to Get Involved

If you're interested in contributing, check out the [NF-PCGR repository](https://github.com/BarryDigby/nf-pcgr) for existing issues and ideas. 
Feel free to join our Slack discussions and submit pull requests!

---

Let's collaborate to improve NF-PCGR and make it a powerful tool for clinical genomics!
