name: Open PR with tools API docs based on webhook call
on:
  workflow_dispatch:
    inputs:
      ref_name:
        description: "The name of the release branch"
        required: true
        default: "dev"

jobs:
  api-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Checkout tools code
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          repository: "nf-core/tools"
          ref: ${{ inputs.ref_name }}
          path: "tools"

      - name: setup node
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: "24"

      - name: Install dependencies
        run: |
          npm install remark unist-util-visit

      - name: setup uv
        uses: astral-sh/setup-uv@08807647e7069bb48b6ef5acd8ec9567f424441b # v8.1.0

      - name: install nf-core
        run: |
          cd tools
          uv sync --all-extras

      - name: run API generation script
        run: |
          cd tools
          uv add sphinx-markdown-builder
          if [ -f docs/api/requirements.txt ]; then
            uv add -r docs/api/requirements.txt
          fi
          uv run bash docs/api/generate-api-docs.sh --release ${{ inputs.ref_name }}

      - name: remove tools code
        run: rm -rf tools

      - uses: j178/prek-action@cbc2f23eb5539cf20d82d1aabd0d0ecbcc56f4e3 # v2
        with:
          install-only: true

      - name: Run prek
        id: pre-commit
        run: git add . && prek run --all-files
        continue-on-error: true

      - name: Commit & push changes
        id: commit-and-push
        run: |
          git config user.email "core@nf-co.re"
          git config user.name "nf-core-bot"
          # restore package.json changes
          git restore package.json
          git restore package-lock.json
          git add .
          git status
          git commit -m "[automated] Update nf-core/tools API docs for ${{ inputs.ref_name }}"

      - name: Create PR
        uses: peter-evans/create-pull-request@5f6978faf089d4d20b00c7766989d076bb2fc7f1 # v8
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Update nf-core/tools API docs for ${{inputs.ref_name}}
          title: Update nf-core/tools API docs for ${{inputs.ref_name}}
          body: |
            This PR updates the nf-core/tools API docs for ${{inputs.ref_name}}.
            Please review the changes and merge if they look good.
          branch: "update-api-docs-${{inputs.ref_name}}"
          delete-branch: true
          base: "main"
          draft: false
