name: Check Broken Links

on:
  schedule:
    - cron: "0 0 * * *" # This will run daily at 00:00

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@f1e137043864b9ab9034ae3a5adc1c108e3f1a48 # v1.4
        id: waitFor200
        with:
          site_name: "nf-core"
          max_timeout: 600 # 10 Minutes
      - name: Check for broken links
        uses: JustinBeckwith/linkinator-action@3d5ba091319fa7b0ac14703761eebb7d100e6f6d # v1
        with:
          paths: "https://deploy-preview-${{github.event.pull_request.number}}--nf-core.netlify.app"
          recurse: true
