name: Check Broken Links

on:
  workflow_dispatch:

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - name: Waiting for 200 from the Netlify Preview
        uses: jakepartusch/wait-for-netlify-action@f1e137043864b9ab9034ae3a5adc1c108e3f1a48 # v1.4
        id: waitFor200
        with:
          site_name: "nf-core"
          max_timeout: 600 # 10 Minutes
      - name: Check for broken links
        uses: JustinBeckwith/linkinator-action@cf305c16947ba91077d8a51fa2cbe155cd60f455 # v2
        with:
          paths: "https://deploy-preview-${{github.event.pull_request.number}}--nf-core.netlify.app"
          recurse: true
