# cloned from https://github.com/nf-core/tools/blob/main/.github/workflows/sync.yml

name: Sync template
on:
  workflow_dispatch:
    inputs:
      nfcore_ref:
        description: 'Version of nf-core/tools to use'
        type: string
        default: '3.2.0'
      pipeline:
        description: 'Pipeline to sync'
        type: string
        default: 'all'
      debug:
        description: 'Enable debug/verbose mode (true or false)'
        type: boolean
        default: false
      make_pr:
        description: 'Make a PR for the sync (true or false)'
        type: boolean
        default: true

# Cancel if a newer run is started
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  get-pipelines:
    runs-on: 'ubuntu-latest'
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - id: set-matrix
        run: |
          if [ "${{ github.event.inputs.testpipeline }}" == "true" ]; then
            echo '{"pipeline":["testpipeline"]}' > pipeline_names.json
          elif [ "${{ github.event.inputs.pipeline }}" != "all" ] && [ "${{ github.event.inputs.pipeline }}" != "" ]; then
            curl -O https://pipelines.tol.sanger.ac.uk/pipeline_names.json
            # check if the pipeline exists
            if ! grep -q "\"${{ github.event.inputs.pipeline }}\"" pipeline_names.json; then
              echo "Pipeline ${{ github.event.inputs.pipeline }} does not exist"
              exit 1
            fi
            echo '{"pipeline":["${{ github.event.inputs.pipeline }}"]}' > pipeline_names.json
          else
            curl -O https://pipelines.tol.sanger.ac.uk/pipeline_names.json
          fi
          cat pipeline_names.json
          echo "matrix=$(cat pipeline_names.json)" >> $GITHUB_OUTPUT

  sync:
    runs-on: 'ubuntu-latest'
    needs: get-pipelines
    strategy:
      matrix: ${{fromJson(needs.get-pipelines.outputs.matrix)}}
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        name: Check out nf-core/tools
        with:
          repository: nf-core/tools
          ref: ${{ github.event.inputs.nfcore_ref }}

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
        name: Check out sanger-tol/${{ matrix.pipeline }}
        with:
          repository: sanger-tol/${{ matrix.pipeline }}
          ref: dev
          token: ${{ secrets.sangertolsoft_access_token }}
          path: sanger-tol/${{ matrix.pipeline }}
          fetch-depth: '0'

      - name: Set up Python 3.12
        uses: actions/setup-python@0b93645e9fea7318ecaed2b359559ac225c90a2b # v5
        with:
          python-version: '3.12'

      - name: Set up Node.js
        uses: actions/setup-node@v4

      - name: Install Prettier
        run: |
          npm install -g prettier@3.3.3

      - name: Install python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install nf-core==${{ github.event.inputs.nfcore_ref }}

      - name: Install Nextflow
        uses: nf-core/setup-nextflow@v2
        with:
          version: 'latest-everything'

      - name: Set Git default branch from nextflow.config and set git default branch to that or "main"

        run: |
          pushd sanger-tol/${{ matrix.pipeline }}
          defaultBranch=$(grep -B5 -A5 "nextflowVersion" nextflow.config | grep "defaultBranch" | cut -d"=" -f2 | sed "s/'//g")
          if [ -z "$defaultBranch" ]; then
            defaultBranch="main"
          fi
          popd
          echo "Default branch: $defaultBranch"
          echo "defaultBranch=$defaultBranch" >> GITHUB_OUTPUT
          git config --global init.defaultBranch $defaultBranch

      - name: Run synchronisation
        env:
          GITHUB_AUTH_TOKEN: ${{ secrets.sangertolsoft_access_token }}
        run: |
          git config --global user.email "105875386+sanger-tolsoft@users.noreply.github.com"
          git config --global user.name "sanger-tolsoft"
          nf-core --log-file sync_log_${{ matrix.pipeline }}.txt \
            ${{ github.event.inputs.debug == 'true' && '--verbose' || '' }} \
            pipelines sync -d sanger-tol/${{ matrix.pipeline }} \
            --from-branch dev \
            ${{ github.event.inputs.make_pr == 'true'  && '--pull-request' || '' }} \
            --username sanger-tolsoft \
            --github-repository sanger-tol/${{ matrix.pipeline }}

      - name: Upload sync log file artifact
        if: ${{ always() }}
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: sync_log_${{ matrix.pipeline }}
          path: sync_log_${{ matrix.pipeline }}.txt
